<?php
/*
 * AP_TT_ : Tab Title
 * AP_TI_ : Tab Info
 * AP_ST_ : Section Title
 * AP_SI_ : Section Info
 * AP_OT_ : Option Title (label)
 * AP_OI_ : Option Info
 * AP_MT_ : Multi Option Title (label)
 * AP_MI_ : Multi Option Info
 * AP_OO_ : Option radio/checkbox/select label
 */
define( 'AP_TT_GENERAL', __( '一般设置', UT_THEME_NAME ) );
define( 'AP_TI_GENERAL', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_HEADER', __( '顶部设置', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_HEADER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_LOGOTYPE', __( '标志设置', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_LOGOTYPE', __( '显示文字/图片作为网站标志', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_HEADER_LOGOTYPE_IMG', __( '图片', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_HEADER_LOGOTYPE_TXT', __( '文字', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_LOGOIMG', __( '图片标志', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_LOGOIMG', __( '上传然后选择一个图片作为你的网站标志', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_LOGOTEXTSIZE', __( '文本标志', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_LOGOTEXTSIZE', __( '文字大小 PX', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_HEADER_FAVICON', __( 'Favourite Icon', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_HEADER_FAVICON', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_404', __( '网站404页', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_404', __( '如果被访问的页面不存在，显示该页面', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_TITLE', __( '标题', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_TITLE', __( '提示：简码可用', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_TEASER', __( '子标题', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_TEASER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_CONTENT', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_CONTENT', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_SIDEBAR', __( '工具栏', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_SIDEBAR', __( '选择显示在404页的小工具', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_404_SIDEBAR_ALIGN', __( '工具栏定位', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_404_SIDEBAR_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_404_SIDEBAR_ALIGN_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_OO_GENERAL_404_SIDEBAR_ALIGN_RIGHT', __( '右边', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_NOPOST', __( '文章404页', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_NOPOST', __( '如果被访问的文章不存在，显示该页面', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_NOPOST_TITLE', __( '标题', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_NOPOST_TITLE', __( '提示：简码可用', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_NOPOST_TEASER', __( '子标题', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_NOPOST_TEASER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_NOPOST_CONTENT', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_NOPOST_CONTENT', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_FOOTER', __( '页脚设置', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_FOOTER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_SIDEBAR', __( '工具栏', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_SIDEBAR', __( '选择显示在页脚的小工具', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_LAYOUT', __( '布局', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_LAYOUT', __( '页脚工具栏样式', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_COPYRIGHT', __( '版权信息', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_COPYRIGHT', __( '输入你网站的版权信息', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_FOOTER_GOOGLEANALYTICS', __( '谷歌分析', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_FOOTER_GOOGLEANALYTICS', __( '输入谷歌分析代码', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_CONTACTFORM', __( '联系方式', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_CONTACTFORM', __( '联系方式简码: [contactform]', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_NAME', __( '姓名', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_NAME', __( '例：姓名', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_MAIL', __( 'E-Mail', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_MAIL', __( '例：E-Mail', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_MESSAGE', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_MESSAGE', __( '例：内容', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_LABEL_SUBMIT', __( '按钮', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_LABEL_SUBMIT', __( '例：提交', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_ERROR_NAME', __( '姓名错误', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_ERROR_NAME', __( '如果用户输入的姓名少于三个字符时，提示用户', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_ERROR_MAIL', __( 'E-Mail错误', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_ERROR_MAIL', __( '如果用户输入的电子邮件错误时，提示用户', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_ERROR_MESSAGE', __( '内容错误', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_ERROR_MESSAGE', __( '如果用户输入的邮件内容少于十个字符，提示用户', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_TO', __( '收信邮箱', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_TO', __( '输入收取信件的邮箱地址，默认是建站时填写的邮箱', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_SUBJECT', __( '邮件默认主题', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_SUBJECT', __( '电子邮件默认主题.', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_ERROR', __( '邮件发送失败', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_ERROR', __( '邮件发送失败，返回信息', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_CONTACTFORM_MAIL_SUCCESS', __( '邮件发送成功', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_CONTACTFORM_MAIL_SUCCESS', __( '邮件发送成功，返回信息', UT_THEME_NAME ) );
	define( 'AP_ST_GENERAL_COMMENTS', __( '评论', UT_THEME_NAME ) );
	define( 'AP_SI_GENERAL_COMMENTS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTSREQ', __( '必填栏目', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTSREQ', __( '设置必填栏目提示信息', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTSMAIL', __( 'E-Mail', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTSMAIL', __( '输入电子邮件不会被公布提示信息', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTSTAGS', __( '允许 HTML', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTSTAGS', __( '评论允许使用HTML标签', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_TXT_COMMENTMOD', __( '审核', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_TXT_COMMENTMOD', __( '评论等待审核中时显示信息', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_ERROR_NAME', __( '昵称错误', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_ERROR_NAME', __( '如果用户输入的昵称少于三个字符长度时，提示用户', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_ERROR_MAIL', __( 'E-Mail错误', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_ERROR_MAIL', __( '如果用户输入的电子邮箱地址错误时，提示用户', UT_THEME_NAME ) );
		define( 'AP_OT_GENERAL_COMMENTS_ERROR_MESSAGE', __( '内容错误', UT_THEME_NAME ) );
		define( 'AP_OI_GENERAL_COMMENTS_ERROR_MESSAGE', __( '如果用户输入的信息少于十个字符时，提示用户', UT_THEME_NAME ) );

define( 'AP_TT_STYLING', __( '样式设置', UT_THEME_NAME ) );
define( 'AP_TI_STYLING', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_BASIC', __( '一般设置', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_BASIC', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_BASIC_THEME_COLOR', __( '主题外观颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_BASIC_THEME_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_BASIC_THEME_FONT', __( '主题字体', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_BASIC_THEME_FONT', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_TOPBAR', __( '顶部', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_TOPBAR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_COLOR', __( '背景颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_IMAGE', __( '背景图片', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_REPEAT', __( '图像填充', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_REPEAT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_REPEAT', __( '全部重复', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_REPEAT-X', __( '填充 X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_REPEAT-Y', __( '填充 Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TOPBAR_BG_REPEAT_NO-REPEAT', __( '不填充', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_BG_POSITION', __( '图片位置', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_BG_POSITION', __( '设置背景图像起始位置，帮助 <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_LINKCOLOR', __( '连接颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_LINKCOLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TOPBAR_LINKCOLOR_H', __( '悬停颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TOPBAR_LINKCOLOR_H', __( '鼠标悬停在连接上显示的颜色', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_HEADER', __( '导航', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_HEADER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_COLOR', __( '背景颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_IMAGE', __( '背景图像', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_REPEAT', __( '图像填充', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_REPEAT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_REPEAT', __( '全部填充', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_REPEAT-X', __( '填充 X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_REPEAT-Y', __( '填充 Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_HEADER_BG_REPEAT_NO-REPEAT', __( '不填充', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_BG_POSITION', __( '图像定位', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_BG_POSITION', __( '设置背景图像起始位置. 帮助 <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_MENUCOLOR', __( '父菜单', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_MENUCOLOR', __( '父菜单的连接颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_SUBMENUCOLOR', __( '子菜单', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_SUBMENUCOLOR', __( '子菜单的连接颜色.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_MENUCOLOR_H', __( '悬停颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_MENUCOLOR_H', __( '鼠标悬停在父菜单时显示的颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_HEADER_SUBMENUCOLOR_H', __( '悬停颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_HEADER_SUBMENUCOLOR_H', __( '鼠标停留在子菜单是显示的颜色', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_TEASER', __( '介绍', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_TEASER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_COLOR', __( '背景颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_IMAGE', __( '背景图像', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_REPEAT', __( '图片填充', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_REPEAT', __( '如何填充背景', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_REPEAT', __( '全部填充', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_REPEAT-X', __( '填充 X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_REPEAT-Y', __( '填充 Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_TEASER_BG_REPEAT_NO-REPEAT', __( '不填充', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_BG_POSITION', __( '图像定位', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_BG_POSITION', __( '背景图像起始位置设置，更多帮助 <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_TEXTCOLOR_TITLE', __( '标题颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_TEXTCOLOR_TITLE', __( '标题文本颜色 (右).', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_TEXTCOLOR_TEASER', __( '预告颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_TEXTCOLOR_TEASER', __( '预告文本颜色(左边).', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_LINKCOLOR', __( '连接颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_LINKCOLOR', __( '基本连接颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_TEASER_LINKCOLOR_H', __( '悬停颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_TEASER_LINKCOLOR_H', __( '鼠标悬停连接是显示颜色', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_CONTENT', __( '内容', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_CONTENT', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_COLOR', __( '背景颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_IMAGE', __( '背景图片', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_REPEAT', __( '填充背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_REPEAT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_REPEAT', __( '全部填充', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_REPEAT-X', __( '填充 X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_REPEAT-Y', __( '填充 Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_CONTENT_BG_REPEAT_NO-REPEAT', __( '不填充', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BG_POSITION', __( '图像定位', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BG_POSITION', __( '背景图像起始位置设置，更多帮助 <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_TEXTCOLOR', __( '文字颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_TEXTCOLOR', __( '基本文字颜色.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINKCOLOR', __( '连接颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINKCOLOR', __( '基本连接颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINKCOLOR_H', __( '悬停颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINKCOLOR_H', __( '鼠标悬停连接是显示颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_PLINKCOLOR', __( '标题颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_PLINKCOLOR', __( '文章和作品的标题颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_PLINKCOLOR_H', __( '悬停颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_PLINKCOLOR_H', __( '鼠标悬停在文章和表示上是显示颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FLINKCOLOR', __( '花式连接', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FLINKCOLOR', __( '花式连接颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FLINKCOLOR_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FLINKCOLOR_H', __( '鼠标悬停在花式连接上是显示的颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_BG', __( '输入框背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_BG', __( '输入框背景颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_TXT', __( '输入框文本', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_TXT', __( '输入框文本颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_BG_F', __( '输入框背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_BG_F', __( '输入内容时背景颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_FIELD_TXT_F', __( '输入框文本', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_FIELD_TXT_F', __( '输入内容是文本颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_BG', __( '按钮背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_BG', __( '联系或搜索的背景颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_TXT', __( '按钮文字', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_TXT', __( '设置联系或搜索的按钮文本颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_BG_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_BG_H', __( '鼠标悬停在联系或搜索背景上时显示的颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_BUTTON_TXT_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_BUTTON_TXT_H', __( '鼠标悬停在联系或搜索的提交按钮上时文本显示的颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINE_COLOR_T', __( '顶部线条', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINE_COLOR_T', __( '设置顶部和底部的线条颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_CONTENT_LINE_COLOR_B', __( '底部线条', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_CONTENT_LINE_COLOR_B', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_FOOTER', __( '页脚', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_FOOTER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_COLOR', __( '背景颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_IMAGE', __( '背景图片', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_REPEAT', __( '填充背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_REPEAT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_REPEAT', __( '全部填充', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_REPEAT-X', __( '填充 X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_REPEAT-Y', __( '填充 Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_FOOTER_BG_REPEAT_NO-REPEAT', __( '不填充', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BG_POSITION', __( '图像定位', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BG_POSITION', __( '背景图像起始位置设置，更多帮助 <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_TEXTCOLOR', __( '文字颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_TEXTCOLOR', __( '基本文字颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_LINKCOLOR', __( '连接颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_LINKCOLOR', __( '基本连接颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_LINKCOLOR_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_LINKCOLOR_H', __( '鼠标悬停连接是显示的颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_BG', __( '输入框背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_BG', __( '输入框背景颜色.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_TXT', __( '输入框文字', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_TXT', __( '输入框文字颜色.', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_BG_F', __( '输入框背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_BG_F', __( '选中该输入框时背景颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_FIELD_TXT_F', __( '输入框文本', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_FIELD_TXT_F', __( '选中该输入框时文章显示颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_BG', __( '按钮背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_BG', __( '联系/搜索体检按钮背景颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_TXT', __( '按钮文字', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_TXT', __( '联系/搜索提交按钮文本颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_BG_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_BG_H', __( '鼠标悬停按钮上时，背景颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_FOOTER_BUTTON_TXT_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_FOOTER_BUTTON_TXT_H', __( '鼠标悬停按钮文字上时，文字颜色', UT_THEME_NAME ) );
	define( 'AP_ST_STYLING_SUBFOOTER', __( '背景颜色', UT_THEME_NAME ) );
	define( 'AP_SI_STYLING_SUBFOOTER', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_COLOR', __( '背景颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_COLOR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_IMAGE', __( '背景图片', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_IMAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_REPEAT', __( '填充背景', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_REPEAT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_REPEAT', __( '全部填充', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_REPEAT-X', __( '填充 X', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_REPEAT-Y', __( '填充 Y', UT_THEME_NAME ) );
			define( 'AP_OO_STYLING_SUBFOOTER_BG_REPEAT_NO-REPEAT', __( '不填充', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_BG_POSITION', __( '图像定位', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_BG_POSITION', __( '背景图像起始位置设置，更多帮助 <a href="http://www.w3.org/TR/CSS2/colors.html#propdef-background-position" target="_blank">w3.org</a>', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_TEXTCOLOR', __( '文字颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_TEXTCOLOR', __( '基本文字颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_LINKCOLOR', __( '连接颜色', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_LINKCOLOR', __( '基本连接颜色', UT_THEME_NAME ) );
		define( 'AP_OT_STYLING_SUBFOOTER_LINKCOLOR_H', __( '悬停', UT_THEME_NAME ) );
		define( 'AP_OI_STYLING_SUBFOOTER_LINKCOLOR_H', __( '鼠标悬停基本连接上时显示的颜色', UT_THEME_NAME ) );

define( 'AP_TT_HOME', __( '首页设置', UT_THEME_NAME ) );
define( 'AP_TI_HOME', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_WELCOME', __( '欢迎词', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_WELCOME', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_WELCOME_TEXT', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_WELCOME_TEXT', __( '输入你的网站欢迎词，这个显示在幻灯片下面 提示：简码可用', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_FEATURED1', __( '服务内容', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_FEATURED1', __( '输入你的网站服务信息，显示在欢迎消息下面，提示：简码可用', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_FEATURED1_ITEM', __( 'Teaser Items', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_FEATURED1_ITEM', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_HEAD', __( '标题', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_HEAD', __( '服务标题，提示：简码可用', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_LINK', __( '连接', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_LINK', __( '这个项目的连接地址', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_TEXT', __( '摘要', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_TEXT', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_ICON', __( '图标', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_ICON', __( '上传并选择一个图标，最大尺寸 70px.', UT_THEME_NAME ) );
			define( 'AP_MT_HOME_FEATURED1_ITEM_OVER', __( '悬停', UT_THEME_NAME ) );
			define( 'AP_MI_HOME_FEATURED1_ITEM_OVER', __( '鼠标悬停在此项目时显示连接按钮, 如 "阅读更多"', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_FEATURED2', __( '最新文章', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_FEATURED2', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_FEATURED2_CATEGORY', __( '分类', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_FEATURED2_CATEGORY', __( '选择至少一个分类，文章将显示在服务下面', UT_THEME_NAME ) );
	define( 'AP_ST_HOME_TWITTER', __( 'Twitter', UT_THEME_NAME ) );
	define( 'AP_SI_HOME_TWITTER', __( '翻译你妹呀，推特被GOV碉堡了', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_USER', __( 'Username', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_USER', __( 'Set the username to show the tweets from.', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_COUNT', __( 'Count', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_COUNT', __( 'How many tweets should be shown?', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_DEFAULT', __( 'Text default', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_DEFAULT', __( 'Auto text for non verb: "i said" bullocks.', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_ED', __( 'Text past', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_ED', __( 'Auto text for past tense: "i" surfed', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_ING', __( 'Text present', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_ING', __( 'Auto tense for present tense: "i was" surfing', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_REPLY', __( 'Text reply', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_REPLY', __( 'Auto tense for replies: "i replied to" @someone "with"', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_URL', __( 'Text url', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_URL', __( 'Auto tense for urls: "i was looking at" http:...', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_TEXT_LOADING', __( 'Text loading', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_TEXT_LOADING', __( 'Optional loading text, displayed while tweets load', UT_THEME_NAME ) );
		define( 'AP_OT_HOME_TWITTER_REFRESH', __( 'Reload Interval', UT_THEME_NAME ) );
		define( 'AP_OI_HOME_TWITTER_REFRESH', __( 'Optional number of seconds after which to reload tweets. "Null" does not reload tweets.', UT_THEME_NAME ) );

define( 'AP_TT_SLIDER', __( '幻灯片设置', UT_THEME_NAME ) );
define( 'AP_TI_SLIDER', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_SLIDER_OPTIONS', __( '设置', UT_THEME_NAME ) );
	define( 'AP_SI_SLIDER_OPTIONS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_HEIGHT', __( '高度', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_HEIGHT', __( '设置幻灯片高度，图片当然也是这个高度咯', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_EFFECT', __( '特效', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_EFFECT', __( '选择幻灯片效果', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_EFFECT_SLIDE', __( '滑动', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_EFFECT_FADE', __( '渐淡', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_AUTOPLAY', __( '自动', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_AUTOPLAY', __( '打开网页幻灯片自动工作', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_AUTOPLAY_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_AUTOPLAY_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_DELAY', __( '延迟', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_DELAY', __( '自动切换幻灯片之间的时间 (1000=1秒).', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_RESUMEDELAY', __( '重复延迟', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_RESUMEDELAY', __( '用户交互幻灯片后恢复 (1000=1秒).', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_ANIMATIONTIME', __( '动画时间', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_ANIMATIONTIME', __( '幻灯片过度需要的时间 (1000=1秒).', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_DELAYBEFOREANIMATE', __( '暂停', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_DELAYBEFOREANIMATE', __( '暂停幻灯片后，需要多久时间再次启动幻灯片', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_OPTIONS_HOVERPAUSE', __( '鼠标停顿', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_OPTIONS_HOVERPAUSE', __( '鼠标悬停是幻灯片停止运行', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_HOVERPAUSE_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_SLIDER_OPTIONS_HOVERPAUSE_N', __( 'No', UT_THEME_NAME ) );
	define( 'AP_ST_SLIDER_ITEMS', __( '管理幻灯片', UT_THEME_NAME ) );
	define( 'AP_SI_SLIDER_ITEMS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SLIDER_ITEMS_ITEM', __( '幻灯片', UT_THEME_NAME ) );
		define( 'AP_OI_SLIDER_ITEMS_ITEM', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CUSTOM', __( '自定义内容', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CUSTOM', __( '你可以添加视频啊或者普通的HTML，留空显示图片', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_IMAGE', __( '图片', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_IMAGE', __( '上传并选择一个图像', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_THUMB', __( '缩略图', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_THUMB', __( '上传并选择图像，绝对大小 80x80px.', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_TITLE', __( '标题', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_TITLE', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_SUBTITLE', __( '附标题', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_SUBTITLE', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_POS', __( '标题位置', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_POS', __( '设置标题出现的位置', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_TOP', __( '顶部', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_RIGHT', __( '右边', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_BOTTOM', __( '底部', UT_THEME_NAME ) );
				define( 'AP_OO_SLIDER_ITEMS_ITEM_CAPTION_POS_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_DIS', __( '标题间距', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_DIS', __( '俩标题之间的间距 单位：px', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_DUR', __( '标题时间', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_DUR', __( '标题在幻灯片中显示多久 (1000=1秒).', UT_THEME_NAME ) );
			define( 'AP_MT_SLIDER_ITEMS_ITEM_CAPTION_EASING', __( '标题特效', UT_THEME_NAME ) );
			define( 'AP_MI_SLIDER_ITEMS_ITEM_CAPTION_EASING', __( '标题在幻灯片中的动画类型', UT_THEME_NAME ) );

define( 'AP_TT_BLOG', __( '博客页设置', UT_THEME_NAME ) );
define( 'AP_TI_BLOG', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_TITLETEASER', __( '文章页', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_TITLETEASER', __( '介绍各页面，显示在导航下方。简码可用。', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_POST_TITLE', __( '标题', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_POST_TITLE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_POST_TEASER', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_POST_TEASER', __( '显示在文章页', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_CATEGORY_TITLE', __( '标题', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_CATEGORY_TITLE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_CATEGORY_TEASER', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_CATEGORY_TEASER', __( '显示在分类页', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_ARCHIVE_TITLE', __( '标题', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_ARCHIVE_TITLE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_ARCHIVE_TEASER', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_ARCHIVE_TEASER', __( '显示在归档页', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_SEARCH_TITLE', __( '标题', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_SEARCH_TITLE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_TITLETEASER_SEARCH_TEASER', __( '内容', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_TITLETEASER_SEARCH_TEASER', __( '显示在搜索页', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_SIDEBAR', __( '默认小工具', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_SIDEBAR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_POST', __( '文章页', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_POST', __( '选择该页调用的小工具', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_POST_ALIGN', __( '位置', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_POST_ALIGN', __( '小工具显示位置', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_POST_ALIGN_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_POST_ALIGN_RIGHT', __( '右边', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_CATEGORY', __( '分类页', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_CATEGORY', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_CATEGORY_ALIGN', __( '位置', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_CATEGORY_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_CATEGORY_ALIGN_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_CATEGORY_ALIGN_RIGHT', __( '右边', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_ARCHIVE', __( '归档页', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_ARCHIVE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_ARCHIVE_ALIGN', __( '位置', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_ARCHIVE_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_ARCHIVE_ALIGN_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_ARCHIVE_ALIGN_RIGHT', __( '右边', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_SEARCH', __( '搜索页', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_SEARCH', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_SIDEBAR_SEARCH_ALIGN', __( '位置', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_SIDEBAR_SEARCH_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_SEARCH_ALIGN_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_SIDEBAR_SEARCH_ALIGN_RIGHT', __( '右边', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_LISTING', __( '文章列表', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_LISTING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_LENGTH', __( '摘要长度', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_LENGTH', __( '显示摘要数，不知道支不支持中文', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_READMORE', __( '阅读更多', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_READMORE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_NEXTLINK', __( '下一页', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_NEXTLINK', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_LISTING_PREVLINK', __( '上一页', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_LISTING_PREVLINK', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_THUMB', __( '缩略图', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_THUMB', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_THUMB_HEIGHT_WSB', __( '高度', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_THUMB_HEIGHT_WSB', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_THUMB_HEIGHT_NSB', __( '宽度', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_THUMB_HEIGHT_NSB', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_THUMB_CROP', __( '裁剪图片', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_THUMB_CROP', __( '选择 "No" 通过比列调整缩略图大小（或许会扭曲图片） 选择"Yes" 通过剪切图片 (不管是俩侧还是顶部或者底部).', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_THUMB_CROP_Y', __( 'yes (推荐)', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_THUMB_CROP_N', __( 'No', UT_THEME_NAME ) );
	define( 'AP_ST_BLOG_READING', __( '阅读', UT_THEME_NAME ) );
	define( 'AP_SI_BLOG_READING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_DISABLE_AUTOP', __( '自动获取标签', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_DISABLE_AUTOP', __( '自动获取文章标签，启用后使用&lt;p&gt;将会扰乱布局.建议使用简码[p][/p] 或 [br]代替', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_DISABLE_AUTOP_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_DISABLE_AUTOP_NO', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_PASSPOST', __( '文章已加密', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_PASSPOST', __( '例：该文章受密码保护，请输入密码查看', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_COMMENTSHIDE', __( '隐藏关闭的评论', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_COMMENTSHIDE', __( '如果文章禁用这篇文章评论，选择"Yes" 可以隐藏注释', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_TXT_COMMENTSHIDE_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_BLOG_READING_TXT_COMMENTSHIDE_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_COMMENTSCLOSED', __( '评论被关闭', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_COMMENTSCLOSED', __( '例：改文章不允许评论', UT_THEME_NAME ) );
		define( 'AP_OT_BLOG_READING_TXT_PASSCOMM', __( '评论已加密', UT_THEME_NAME ) );
		define( 'AP_OI_BLOG_READING_TXT_PASSCOMM', __( '例：该评论受密码保护，请输入密码查看', UT_THEME_NAME ) );

define( 'AP_TT_PAGES', __( '页面设置', UT_THEME_NAME ) );
define( 'AP_TI_PAGES', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_PAGES_TITLETEASER', __( '页面描述', UT_THEME_NAME ) );
	define( 'AP_SI_PAGES_TITLETEASER', __( '默认页面描述，简码可用', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_TITLETEASER_TEASER', __( '页面描述', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_TITLETEASER_TEASER', __( '输入默认页面描述，可以被覆盖', UT_THEME_NAME ) );
	define( 'AP_ST_PAGES_SIDEBAR', __( '默认小工具', UT_THEME_NAME ) );
	define( 'AP_SI_PAGES_SIDEBAR', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_SIDEBAR_SIDEBAR', __( '页面', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_SIDEBAR_SIDEBAR', __( '设置页面调用的小工具', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_SIDEBAR_ALIGN', __( '位置', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_SIDEBAR_ALIGN', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_SIDEBAR_ALIGN_LEFT', __( '左边', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_SIDEBAR_ALIGN_RIGHT', __( '右边', UT_THEME_NAME ) );
	define( 'AP_ST_PAGES_READING', __( '阅读', UT_THEME_NAME ) );
	define( 'AP_SI_PAGES_READING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_DISABLE_AUTOP', __( '自动获取标签', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_DISABLE_AUTOP', __( '自动获取文章标签，启用后使用&lt;p&gt;将会扰乱布局.建议使用简码[p][/p] 或 [br]代替', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_DISABLE_AUTOP_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_DISABLE_AUTOP_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_COMMENTSHIDE', __( '隐藏已关闭的评论', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_COMMENTSHIDE', __( '如果文章禁用这篇文章评论，选择"Yes" 可以隐藏注释', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_TXT_COMMENTSHIDE_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_PAGES_READING_TXT_COMMENTSHIDE_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_COMMENTSCLOSED', __( '评论已关闭', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_COMMENTSCLOSED', __( '例：该文章不允许发表评论', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_PASSPOST', __( '评论已加密', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_PASSPOST', __( '例：该评论受密码保护，请输入密码查看', UT_THEME_NAME ) );
		define( 'AP_OT_PAGES_READING_TXT_PASSCOMM', __( '评论已加密', UT_THEME_NAME ) );
		define( 'AP_OI_PAGES_READING_TXT_PASSCOMM', __( '例：该评论受密码保护，请输入密码查看', UT_THEME_NAME ) );

define( 'AP_TT_PORTFOLIO', __( '作品页设置', UT_THEME_NAME ) );
define( 'AP_TI_PORTFOLIO', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_GENERAL', __( '一般设置', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_GENERAL', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_GENERAL_LAYOUT', __( '默认布局', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_GENERAL_LAYOUT', __( '选择作品页的默认布局，每个分类可自定义', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_FILT', __( 'Filter', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_1COL', __( '1 Column', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_2COL', __( '2 Column', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_3COL', __( '3 Column', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_GENERAL_LAYOUT_4COL', __( '4 Column', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_GENERAL_READMORE', __( '阅读更多', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_GENERAL_READMORE', __( '像阅读更多的连接文本, 例如 "阅读更多"', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_GENERAL_LINKTEXT', __( '连接文本', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_GENERAL_LINKTEXT', __( '像查看作品的连接文本, 例如 "查看作品"', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_TITLETEASER', __( '标题和摘要', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_TITLETEASER', __( '默认标题和再要，简码可用', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_WORK_TITLE', __( '作品名', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_WORK_TITLE', __( '作品默认名称', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_WORK_TEASER', __( '摘要', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_WORK_TEASER', __( '作品默认再要，可以替换', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_CATEGORY_TITLE', __( '分类名', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_CATEGORY_TITLE', __( '分类名称.可以被分类本身名称替换', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_TITLETEASER_CATEGORY_TEASER', __( '分类描述', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_TITLETEASER_CATEGORY_TEASER', __( '分类默认描述，可以被分类本身描述替换', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_THUMB', __( '缩略图', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_THUMB', __( '不建议修改，使用默认就好，除非你很了解他', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_FILT', __( '高度', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_FILT', __( 'Thumbnail height in px for filter layout. Width fixed to: 318px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_FILT', __( 'Filter Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_FILT', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_FILT_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_FILT_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_1COL', __( '1 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_1COL', __( 'Thumbnail height in px for 1 column layout. Width fixed to: 626px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_1COL', __( '1 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_1COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_1COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_1COL_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_2COL', __( '2 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_2COL', __( 'Thumbnail height in px for 2 column layout. Width fixed to: 462px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_2COL', __( '2 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_2COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_2COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_2COL_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_3COL', __( '3 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_3COL', __( 'Thumbnail height in px for 3 column layout. Width fixed to: 298px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_3COL', __( '3 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_3COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_3COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_3COL_N', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_HEIGHT_4COL', __( '4 Column Thumb Height', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_HEIGHT_4COL', __( 'Thumbnail height in px for 4 column layout. Width fixed to: 216px.', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_THUMB_CROP_4COL', __( '4 Column Crop Thumb', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_THUMB_CROP_4COL', __( '', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_4COL_Y', __( 'Yes (recommend)', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_THUMB_CROP_4COL_N', __( 'No', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_LISTING', __( '列表', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_LISTING', __( '不建议修改，使用默认就好，除非你很了解他', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_FILT', __( 'Count Filter', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_FILT', __( 'How many works to show on filter layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_1COL', __( 'Count 1 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_1COL', __( 'How many works to show on 1 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_1COL', __( 'Length 1 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_1COL', __( 'How many words to show on 1 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_2COL', __( 'Count 2 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_2COL', __( 'How many works to show on 2 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_2COL', __( 'Length 2 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_2COL', __( 'How many words to show on 2 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_3COL', __( 'Count 3 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_3COL', __( 'How many works to show on 3 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_3COL', __( 'Length 3 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_3COL', __( 'How many words to show on 3 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_COUNT_4COL', __( 'Count 4 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_COUNT_4COL', __( 'How many works to show on 4 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_LENGTH_4COL', __( 'Length 4 Column', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_LENGTH_4COL', __( 'How many words to show on 4 column layout?', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_NEXTTEXT', __( '下一页', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_NEXTTEXT', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_LISTING_PREVTEXT', __( '上一页', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_LISTING_PREVTEXT', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_PORTFOLIO_READING', __( '阅读', UT_THEME_NAME ) );
	define( 'AP_SI_PORTFOLIO_READING', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_READING_DISABLE_AUTOP', __( '自动获取标签', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_READING_DISABLE_AUTOP', __( '自动获取文章标签，启用后使用&lt;p&gt;将会扰乱布局.建议使用简码[p][/p] 或 [br]代替', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_READING_DISABLE_AUTOP_Y', __( 'Yes', UT_THEME_NAME ) );
			define( 'AP_OO_PORTFOLIO_READING_DISABLE_AUTOP_NO', __( 'No', UT_THEME_NAME ) );
		define( 'AP_OT_PORTFOLIO_READING_TXT_PASSPOST', __( '密码文本', UT_THEME_NAME ) );
		define( 'AP_OI_PORTFOLIO_READING_TXT_PASSPOST', __( '作品为受密码保护的', UT_THEME_NAME ) );

define( 'AP_TT_SOCIAL', __( '社会联系', UT_THEME_NAME ) );
define( 'AP_TI_SOCIAL', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_SOCIAL_OPTIONS', __( '选择社会联系', UT_THEME_NAME ) );
	define( 'AP_SI_SOCIAL_OPTIONS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_OPTIONS_HEADER', __( '顶部', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_OPTIONS_HEADER', __( '显示社会联系连接在你网站的导航上方。', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_HEADER_Y', __( 'yes', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_HEADER_N', __( 'no', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_OPTIONS_FOOTER', __( '底部', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_OPTIONS_FOOTER', __( '显示社会联系连接在你网站的页脚', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_FOOTER_Y', __( 'yes', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_FOOTER_N', __( 'no', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_OPTIONS_OPEN', __( '打开连接', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_OPTIONS_OPEN', __( '如何打开这个社会连接', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_OPEN_SAME', __( '本窗口', UT_THEME_NAME ) );
			define( 'AP_OO_SOCIAL_OPTIONS_OPEN_NEW', __( '新窗口', UT_THEME_NAME ) );
	define( 'AP_ST_SOCIAL_LINKS', __( '编辑社会连接', UT_THEME_NAME ) );
	define( 'AP_SI_SOCIAL_LINKS', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SOCIAL_LINKS_LINK', __( '社会连接', UT_THEME_NAME ) );
		define( 'AP_OI_SOCIAL_LINKS_LINK', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SOCIAL_LINKS_LINK_NAME', __( '名称', UT_THEME_NAME ) );
			define( 'AP_MI_SOCIAL_LINKS_LINK_NAME', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SOCIAL_LINKS_LINK_LINK', __( '连接', UT_THEME_NAME ) );
			define( 'AP_MI_SOCIAL_LINKS_LINK_LINK', __( '', UT_THEME_NAME ) );

define( 'AP_TT_FONTS', __( '字体设置', UT_THEME_NAME ) );
define( 'AP_TI_FONTS', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_FONTS_MANAGE', __( '管理字体', UT_THEME_NAME ) );
	define( 'AP_SI_FONTS_MANAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_FONTS_MANAGE_FONT', __( '字体', UT_THEME_NAME ) );
		define( 'AP_OI_FONTS_MANAGE_FONT', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_FONTS_MANAGE_FONT_NAME', __( '名称', UT_THEME_NAME ) );
			define( 'AP_MI_FONTS_MANAGE_FONT_NAME', __( '字体名称，自动添加在样式表', UT_THEME_NAME ) );
			define( 'AP_MT_FONTS_MANAGE_FONT_URL', __( '地址', UT_THEME_NAME ) );
			define( 'AP_MI_FONTS_MANAGE_FONT_URL', __( '样式表地址.', UT_THEME_NAME ) );
			define( 'AP_MT_FONTS_MANAGE_FONT_ALT', __( '替补字体', UT_THEME_NAME ) );
			define( 'AP_MI_FONTS_MANAGE_FONT_ALT', __( '当前者字体不存在，那么那么就调用第二个字体，以此类推.逗号分离多个字体, 如 "雅黑", "宋体", "楷体"', UT_THEME_NAME ) );

define( 'AP_TT_SIDEBARS', __( '工具栏设置', UT_THEME_NAME ) );
define( 'AP_TI_SIDEBARS', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_SIDEBARS_MANAGE', __( '管理工具栏', UT_THEME_NAME ) );
	define( 'AP_SI_SIDEBARS_MANAGE', __( '', UT_THEME_NAME ) );
		define( 'AP_OT_SIDEBARS_MANAGE_SIDEBAR', __( '工具栏', UT_THEME_NAME ) );
		define( 'AP_OI_SIDEBARS_MANAGE_SIDEBAR', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_SIDEBARS_MANAGE_SIDEBAR_NAME', __( '工具栏标题', UT_THEME_NAME ) );
			define( 'AP_MI_SIDEBARS_MANAGE_SIDEBAR_NAME', __( '给工具栏起一个名字', UT_THEME_NAME ) );
			define( 'AP_MT_SIDEBARS_MANAGE_SIDEBAR_DESCRIPTION', __( '工具栏描述', UT_THEME_NAME ) );
			define( 'AP_MI_SIDEBARS_MANAGE_SIDEBAR_DESCRIPTION', __( '可选项 工具栏描述', UT_THEME_NAME ) );

define( 'AP_TT_BOXES', __( '消息框自定义', UT_THEME_NAME ) );
define( 'AP_TI_BOXES', __( '', UT_THEME_NAME ) );
	define( 'AP_ST_BOXES_ITEMS', __( '自定义消息框', UT_THEME_NAME ) );
	define( 'AP_SI_BOXES_ITEMS', __( '添加自定义消息框，简码', UT_THEME_NAME ) );
		define( 'AP_OT_BOXES_ITEMS_ITEM', __( '', UT_THEME_NAME ) );
		define( 'AP_OI_BOXES_ITEMS_ITEM', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_NAME', __( '名称', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_NAME', __( '样列<br />[box style="the_name"]', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_ICON', __( '图标', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_ICON', __( '上传然后再选择图标，大小必须为32x32px.', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_COL-BG', __( '背景颜色', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_COL-BG', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_COL-BD', __( '边缘颜色', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_COL-BD', __( '', UT_THEME_NAME ) );
			define( 'AP_MT_BOXES_ITEMS_ITEM_COL-TX', __( '文字颜色', UT_THEME_NAME ) );
			define( 'AP_MI_BOXES_ITEMS_ITEM_COL-TX', __( '', UT_THEME_NAME ) );

?>